server:
  port: 8070
spring:
  application:
    name: productServeice #The same name as the file yml in the config-server
  datasource:
    url: jdbc:mysql://localhost:3306/productServiceYT-AXON?createDatabaseIfNotExist=true
    username: root
    password: mimi019mimi
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.MySQLDialect

axon:
  eventhandling:
    processors:
      default:
        mode: tracking
        source: eventStore
        initial-segment-count: 1
